### ISSUE TITLE
Does not support chinese

### ISSUE THREAD

**Issue by zelda0079** [RubenHuizenga/super-mission-stats-viewer#23]
Cound you test this json?
I cannot see anything in the viewer.

{"MissionInfo":{"Seed":44029,"Complexity":0,"Duration":0,"Mutator":"採礦天堂","DNA":"DNA_Motherlode_Long_C","Structure":"SingleMission","MissionType":"定點採集","Primary":"採集水痕碑石","Warnings":[],"Secondaries":["收集暴露蘑菇"],"Hazard":"危害級別 5   致命","Name":"不健康的 巡邏","IsDeepdive":false,"StartDateTime":"2023年12月30日 上午10:59:31","GlobalSeed":10013956,"Biome":"毒菌沼地"},"PlayerStats":{"IsHost":true,"Name":"zelda","Hero":"偵察兵","PlayerRank":509,"HeroLevel":18,"Promotions":15,"TotalDeaths":3,"TotalRevives":0,"TotalTimeDown":37739.0,"DamageDealt":{"酸液濺射螂蛛":571.390137,"搏擊螂蛛":7749.710449,"刀鋒搏擊螂蛛":2264.797363,"劫掠螂蠅":394.0,"瘴甲螂蛛":3315.099609,"嗜礦怪蟲":361.75,"近衛搏擊螂蛛":3035.268799,"螂蛛幼蟲":113.119995,"巨爆金蛛":1162.5,"螂蛛母巢":664.589966,"蟲網濺射螂蛛":609.340027,"小型螂蛛":99.0,"珂賽特酸液濺射螂蛛":2055.502197,"科羅納背甲獸":786.02002,"聖誕妖精":238.339996,"腐泡噴濺螂蛛":338.859955,"暴君螂蛛":599.180298},"EnemiesKilled":{"酸液濺射螂蛛":5,"搏擊螂蛛":91,"瘴甲螂蛛":4,"螂蛛幼蟲":18,"刀鋒搏擊螂蛛":15,"巨爆金蛛":1,"近衛搏擊螂蛛":9,"蟲網濺射螂蛛":14,"小型螂蛛":8,"珂賽特酸液濺射螂蛛":5,"聖誕妖精":1,"腐泡噴濺螂蛛":1,"科羅納背甲獸":1},"FlaresThrown":101,"Jumps":423,"DamageTaken":800.028137,"Pings":37,"TimesResupplied":2,"MuleCalls":1,"Shouts":2,"MostSingleHitDamage":183.339996,"DPS":18.985556,"LongestTimeAlive":642029.0,"Title":"Light Bringer"},"MissionResult":{"MissionTime":1283,"Credits":{"完成主要目標":1774,"完成次要目標":546,"珂賽特感染":682,"2 x 生存獎勵":819,"64 x 黃金 採集量":349},"WasSuccess":true,"XP":{"完成主要目標":4777,"完成次要目標":1911,"珂賽特感染":2730,"隊伍採集礦物":2005,"隊伍擊殺總數":351},"EndscreenResources":{"紫晶石":440.0,"翡翠石":229.0}}}

**Comment by zelda0079** [comment]
[1700692712.txt](https://github.com/RubenHuizenga/super-mission-stats-viewer/files/13914838/1700692712.txt)

**Comment by RubenHuizenga** [comment]
Alrighty, just made a new release which should hopefully fix the issue
